### PR TITLE
attr access for schemes configuration, fixes #7

### LINKED ISSUE #7: https failing
As seen in issue https://github.com/swagger-api/swagger-ui/issues/1957

Is there a way to change is in the implementation of swagger-ui?

### PR DESCRIPTION
**Pull request by zkwentz**

### CODE REVIEW

**Comment by zkwentz** [comment]
Add `config.schemes = [:https]` to your swaggard initializer.

**Comment by adrian-gomez** [comment]
@zkwentz you are adding this new option but its not getting used anywhere, maybe you forgot to add some file to the commit?

**Comment by adrian-gomez** [comment]
@zkwentz if this was to add support for https I have released a new version that uses the latest version from swagger-ui. You might want to give that one a try

**Comment by adrian-gomez** [comment]
@zkwentz I'm closing this one as I pushed the same code. I didn't notice I missed the attr writer the first time :S. Thanks for pointing this out!

**Pull request closed without merging**
