### PR TITLE
Fixed NS_ERROR_MALFORMED_URI / Invalid URL error

### PR DESCRIPTION
**Pull request by redbar0n**
Fixed examples of api_base_path, updated swagger-ui version from 2.2.8 to 2.2.10, and removed doc_base_path since it was unused.

### CODE REVIEW

**Comment by redbar0n** [comment]
Ref this issue: https://github.com/adrian-gomez/swaggard/issues/25

**Comment by redbar0n** [comment]
Made some other changes too. See the fairly detailed description in the commit msgs. Wanted to make a separate pull request for them, but it seems they got added to this one.

**Comment by adrian-gomez** [comment]
@redbar0n would you mind taking out the update to swagger ui? I'll like to do that one myself, the rest of the changes seem to be ok

**Comment by redbar0n** [comment]
Ah, I didn't notice the failed test before now. I fixed it now, so test runs green, and pushed to my fork. I see it got included here in this PR as well.

I could take the update to swagger ui and the related test completely out of the pull request, of course. But how do I do that? :)

**Comment by redbar0n** [comment]
@adrian-gomez how does it look now?

**Comment by adrian-gomez** [comment]
@redbar0n sorry for the delayed response, I'm testing this one locally and if all goes well I'll merge it :D

**Pull request merged**
